### ISSUE TITLE
Make all model classes partial

### ISSUE THREAD

**Issue by ivarne** [Altinn/altinn-studio-cli#23]
### Description

As part of https://github.com/Altinn/app-frontend-react/issues/1812, and in order to make the source generator work https://github.com/Altinn/app-lib-dotnet/issues/435, we need all model classes (at minimum every one used in a `List<T>`) needs to be declared as `partial`

I'm also considering adding the attribute `[AltinnRowId]` when declaring this partial, in order to make the source generator more universally usable and not require heuristics to figure out what classes are list items in a data model.

### Additional Information

Studio will also need to implement this change every time they generate data models.

**Comment by RonnyB71** [comment]
Won't use this solution, closing the issue.
